# Generated by Django 6.0.4 on 2026-04-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ACT', 'Acción'), ('COM', 'Comedia'), ('DRM', 'Drama'), ('SCI', 'Ciencia Ficción'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('ANI', 'Animación'), ('AVN', 'Aventura'), ('FAN', 'Fantasía'), ('MUS', 'Musical'), ('DEF', 'Default')], default='DEF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_lanzamiento', models.DateField()),
                ('pais_origen', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=1000)),
                ('duracion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('gross', models.CharField(max_length=255)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peliculas.estudio')),
                ('generos', models.ManyToManyField(to='peliculas.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='peliculas.pelicula')),
                ('texto', models.TextField(max_length=1000)),
            ],
        ),
    ]
