# Generated by Django 6.0.4 on 2026-04-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('pais', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ACT', 'Actor'), ('DIR', 'Director'), ('PRO', 'Productor'), ('ESC', 'Escritor')], default='ACT', max_length=50)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.persona')),
            ],
        ),
    ]
