# Generated by Django 6.0.4 on 2026-04-23 18:12

from django.db import migrations

GENEROS = [
    ('ACT', 'Acción'),
    ('COM', 'Comedia'),
    ('DRM', 'Drama'),
    ('SCI', 'Ciencia Ficción'),
    ('HOR', 'Horror'),
    ('ROM', 'Romance'),
    ('ANI', 'Animación'),
    ('AVN', 'Aventura'),
    ('FAN', 'Fantasía'),
    ('MUS', 'Musical'),
    ('DEF', 'Default'),
]

def poblar_generos(apps, schema_editor):
    Genero = apps.get_model('peliculas', 'Genero')
    for codigo, nombre in GENEROS:
        Genero.objects.get_or_create(nombre=codigo)

def eliminar_generos(apps, schema_editor):
    Genero = apps.get_model('peliculas', 'Genero')
    Genero.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_alter_pelicula_imagen_alter_persona_imagen'),
    ]

    operations = [
        migrations.RunPython(poblar_generos, eliminar_generos)
    ]
