# Generated by Django 6.0.4 on 2026-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_poblar_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(choices=[('ACT', 'Acción'), ('COM', 'Comedia'), ('DRM', 'Drama'), ('SCI', 'Ciencia Ficción'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('ANI', 'Animación'), ('AVN', 'Aventura'), ('FAN', 'Fantasía'), ('MUS', 'Musical'), ('DEF', 'Default')], default='DEF', max_length=3, unique=True),
        ),
    ]
