# Generated by Django 6.0.4 on 2026-04-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_remove_usuario_reviews_alter_resena_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='peliculas.pelicula')),
                ('texto', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.CharField(default='Anónimo', max_length=100),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.review')),
            ],
        ),
    ]
